[book]
title = "Scaphandre documentation"
description = "Extensible and lightweight monitoring agent for energy consumption metrics"
authors = ["Benoit Petit"]
language = "en"
src = "docs_src"

[build]
build-dir = "../scaphandre-documentation/docs"

[rust]
edition = "2018"

[output.html]
mathjax-support = false
site-url = "/docs/"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
