{
 "title": "EMSEOS Energy dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Energy overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Energy (CPU + GPU)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(scaph_process_power_consumption_microwatts{container_id=~\"containerd://.*|cri-containerd-.*\"}[$__range]) * $__range_s / 1000000)",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(avg_over_time(DCGM_FI_DEV_POWER_USAGE[$__range]) * $__range_s)",
     "legendFormat": "GPU"
    }
   ]
  },
  {
   "title": "Top 10 consuming Pods (5m window)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  label_replace(\r\n    topk(10, avg_over_time(scaph_process_power_consumption_microwatts{container_id=~\"containerd://.*|cri-containerd-.*\"}[5m]) * 300 / 1000000),\r\n    \"container_id\",\r\n    \"containerd://$1\",\r\n    \"container_id\",\r\n    \"cri-containerd-(.*)\"\r\n  )\r\n  * on(container_id) group_left(pod)\r\n  kube_pod_container_info{container_id=~\"containerd://.*|cri-containerd-.*\"}\r\n)\r\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Energy by GPU (5m window)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "expr": "sum by (gpu) (\r\n  avg_over_time(DCGM_FI_DEV_POWER_USAGE[5m]) * 300\r\n)\r\n",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "CPU vs. GPU Energy (15s window)",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(scaph_process_power_consumption_microwatts{container_id=~\"containerd://.*|cri-containerd-.*\"}[15s]) / 1000000) * 15\r\n",
     "legendFormat": "CPU Energy"
    },
    {
     "expr": "sum(avg_over_time(DCGM_FI_DEV_POWER_USAGE[15s])) * 15\r\n",
     "legendFormat": "GPU Energy"
    }
   ]
  },
  {
   "title": "CPU vs. GPU Energy (15s window)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(scaph_process_power_consumption_microwatts{container_id=~\"containerd://.*|cri-containerd-.*\"}[15s]) / 1000000) * 15\r\n",
     "legendFormat": "CPU Energy"
    },
    {
     "expr": "sum(avg_over_time(DCGM_FI_DEV_POWER_USAGE[15s])) * 15\r\n",
     "legendFormat": "GPU Energy"
    }
   ]
  },
  {
   "title": "Cumulative CPU & GPU Energy",
   "type": "barchart",
   "description": "Energy calculated using 15s window",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(scaph_process_power_consumption_microwatts{container_id=~\"containerd://.*|cri-containerd-.*\"}[15s]) / 1000000) * 15\r\n",
     "legendFormat": "CPU Energy"
    },
    {
     "expr": "sum(avg_over_time(DCGM_FI_DEV_POWER_USAGE[15s])) * 15\r\n",
     "legendFormat": "GPU Energy"
    }
   ]
  },
  {
   "title": "CPU vs. GPU power over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(scaph_process_power_consumption_microwatts{container_id=~\"containerd://.*|cri-containerd-.*\"}  / 1000000)",
     "legendFormat": "CPU Power"
    },
    { "expr": "sum(DCGM_FI_DEV_POWER_USAGE)", "legendFormat": "GPU Power" }
   ]
  },
  {
   "title": "CPU vs. GPU usage over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(scaph_process_cpu_usage_percentage)",
     "legendFormat": "CPU"
    },
    { "expr": "DCGM_FI_DEV_GPU_UTIL", "legendFormat": "GPU {{gpu}}" }
   ]
  },
  {
   "title": "Monitoring agent CPU consumption",
   "type": "gauge",
   "description": "Sum of total CPU consumption of all the pods inside 'ikerlan-monitoring' namespace",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\r\n  label_replace(\r\n    avg_over_time(scaph_process_power_consumption_microwatts[$__range]) * $__range_s / 1000000,\r\n    \"container_id\",\r\n    \"containerd://$1\",\r\n    \"container_id\",\r\n    \"cri-containerd-(.*)\"\r\n  ) * on(container_id) group_left(pod) (\r\n    kube_pod_container_info{namespace=\"ikerlan-monitoring\", container_id=~\"containerd://.*|cri-containerd-.*\"}\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total vs Monitoring agent consumption (15s window)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(scaph_process_power_consumption_microwatts[15s]) * 15 / 1000000)",
     "legendFormat": "Total CPU"
    },
    {
     "expr": "sum(\r\n  sum by (pod) (\r\n  label_replace(\r\n    avg_over_time(scaph_process_power_consumption_microwatts[15s]) * 15 / 1000000,\r\n    \"container_id\",\r\n    \"containerd://$1\",\r\n    \"container_id\",\r\n    \"cri-containerd-(.*)\"\r\n  ) * on(container_id) group_left(pod) (\r\n    kube_pod_container_info{namespace=\"ikerlan-monitoring\", container_id=~\"containerd://.*|cri-containerd-.*\"}\r\n  )\r\n)\r\n)",
     "legendFormat": "MonitoringAgent"
    }
   ]
  }
 ]
}