{
 "title": "Kubernetes power usage using Scaphandre",
 "description": "Show Kubernetes cluster power usage measured with Scaphandre.",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Top 10 Pod consumptions (every 3s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "topk(10, scaph_process_power_consumption_microwatts{container_id=~\".*containerd.*\"} / 1000000)",
     "legendFormat": "{{ exe }}"
    }
   ]
  },
  {
   "title": "Top 10 Pod energy consumptions (windows of 30s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "expr": "topk(10, rate(scaph_process_power_consumption_microwatts{container_id!=\"\"}[30s]) / 1000000)",
     "legendFormat": "{{ exe }}"
    }
   ]
  },
  {
   "title": "Top 10 Process consumptions (every 3s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "topk(10, scaph_process_power_consumption_microwatts / 1000000)",
     "legendFormat": "{{ exe }}"
    }
   ]
  },
  {
   "title": "Node CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{ exe }}"
    }
   ]
  },
  {
   "title": "Node power consumption (every 3s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "scaph_host_power_microwatts / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scaphandre",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "scaph_process_power_consumption_microwatts{exe=\"scaphandre\"} / 1000000",
     "legendFormat": "{{ kubernetes_node }}"
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "scaph_process_power_consumption_microwatts{exe=\"grafana-server\"} / 1000000",
     "legendFormat": "{{ kubernetes_node }}"
    }
   ]
  },
  {
   "title": "Node power vs CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "scaph_host_power_microwatts / 1000000",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "scaph_process_power_consumption_microwatts{exe=\"prometheus\"} / 1000000",
     "legendFormat": "{{ kubernetes_node }}"
    }
   ]
  },
  {
   "title": "Kubernetes Control Plane",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "scaph_process_power_consumption_microwatts{exe=~\"etcd|kube-apiserver|kube-controller|kube-proxy|kube-scheduler|kubelet\"} / 1000000",
     "legendFormat": "{{ exe }}"
    }
   ]
  },
  {
   "title": "Docker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "scaph_process_power_consumption_microwatts{exe=\"dockerd\"} / 1000000",
     "legendFormat": "{{ kubernetes_node }}"
    }
   ]
  }
 ]
}