apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "scaphandre.name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "scaphandre.name" . }}
  template:
    metadata:
      name: {{ template "scaphandre.name" . }}
      labels:
        {{- include "labels.common" . | nindent 8 }}
    spec:
      containers:
      - name:  {{ template "scaphandre.name" . }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        args:
          - {{.Values.scaphandre.command }}
          {{- range $key, $value :=.Values.scaphandre.args }}
          {{- if $value }}
          - {{ $value }} # modified
          {{- else }}
          - --{{ $key }}
          {{- end }}
          {{- end }}
          {{- range $key, $value :=.Values.scaphandre.extraArgs }}
          {{- if $value }}
          - --{{ $key }}={{ $value }}
          {{- else }}
          - --{{ $key }}
          {{- end }}
          {{- end }}
        env:
        {{- if .Values.scaphandre.rustBacktrace }}
        - name: RUST_BACKTRACE
          value: '{{ .Values.scaphandre.rustBacktrace }}'
        {{- end }}
        ports:
        - name: metrics
          containerPort: {{ .Values.port }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - mountPath: /proc
          name: proc
          readOnly: false
        - mountPath: /sys/class/powercap
          name: powercap
          readOnly: false
        - mountPath: /run/containerd/containerd.sock
          name: containerd-socket
        securityContext:
          privileged: true  # To avoid 'permission denied' error
      serviceAccountName: {{ template "scaphandre.name" . }}
      tolerations:
      # Tolerate all taints for observability
      - operator: "Exists"
      volumes: # needed
      - hostPath:
          path: /proc
          type: "Directory"
        name: proc
      - hostPath:
          path: /sys/class/powercap
          type: "Directory"
        name: powercap
      - name: containerd-socket
        hostPath:
          path: /run/containerd/containerd.sock
          type: Socket
