{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "scaphandre.name" . }}-service-monitoring
  {{- if .Values.serviceMonitor.namespace }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ template "scaphandre.name" . }}
spec:
  endpoints:
    - path: /metrics
      port: metrics
      scheme: http
      {{- if .Values.serviceMonitor.interval }}
      interval: {{ .Values.serviceMonitor.interval }}
      {{- end }}
      scrapeTimeout: 3s
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "scaphandre.name" . }}
{{- end }}
